---
- name: Create Team Role User
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    org_id: 1
    aap_host: 192.168.122.10
    
  tasks:
    - name: Import varaible
      ansible.builtin.include_role: 
        name: ../roles/add_team_role_user