---
- name: Create Team Role User
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    org_id: 1
    aap_host: 192.168.122.10
    controller_validate_certs: false
    
  tasks:

    - name: Create Team 
      ansible.controller.team:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "redhat"
        name: "ABC-Squad1-WorkFlowTemplate-Admin"
        organization: 1
        state: present
        validate_certs: false

    - name: Create Team User
      ansible.controller.role:
        controller_host: "{{ aap_host }}"
        controller_username: "admin"
        controller_password: "redhat"
        user: user03
        target_team: "ABC-Squad1-WorkFlowTemplate-Admin"
        role: member
        state: present
        validate_certs: false
        #role: admin
        #team: "ABC-Squad1-WorkFlowTemplate-Admin"
        #organization: 1
        #validate_certs: false

    #- name: Import varaible
    #  ansible.builtin.include_role: 
    #    name: ../roles/add_team_role_user