---
- name: Show item
  ansible.builtin.debug: var=team_role

- name: Create Team Role Job Template
  ansible.builtin.include_tasks:
    file: 03-01-add-team-to-job-template.yaml
  when: team_role.resource_type == 'job_template'

- name: Create Team Role Job Template
  ansible.builtin.include_tasks:
    file: 03-02-add-team-to-workflow-template.yaml
  when: team_role.resource_type == 'workflow_job_template'

