---
- name: Create Team 
  ansible.controller.team:
    controller_host: "{{ aap_host }}"
    controller_username: "admin"
    controller_password: "redhat"
    name: "ABC-Squad1-WorkFlowTemplate-Admin"
    organization: 1
    state: present
    validate_certs: false

- name: Create Team User
  ansible.controller.role:
    controller_host: "{{ aap_host }}"
    controller_username: "admin"
    controller_password: "redhat"
    #user: user03-admin
    #target_team: "ABC-Squad1-WorkFlowTemplate-Admin"
    #role: member
    team: "ABC-Squad1-WorkFlowTemplate-Admin"
    organization: 1
    state: present
    validate_certs: false
  #loop: "{{ team_user.user }}"
  #user: user03-admin "{{ item }}"
  #target_team: "{{ team_user.team }}"