---
- name: Collect Job Template ID and Name
  ansible.builtin.include_tasks:
    file: 01-collection-job-template-info.yaml

- name: Collect WorkFlow Job Template ID and Name
  ansible.builtin.include_tasks:
    file: 02-collection-workflow-template-info.yaml

- name: Create Team Role
  ansible.builtin.include_tasks:
    file: 03-add-team-role-to-template.yaml
  loop: "{{ expected_team_role  }}"
  loop_control:
    loop_var: team_role

#- name: Collect User Info
#  ansible.builtin.include_tasks:
#    file: 04-collection-user-info.yaml



#- name: Create Team Role
#  ansible.builtin.include_tasks:
#    file: 05-add-team-user.yaml
#  loop: "{{ expected_team_member }}"
#  loop_control:
#    loop_var: team_user

