---
- name: GIC infor collection
  hosts: all
  connection: ssh
  become: yes
  gather_facts: true

  roles:
    - jin.test.test

  tasks:
    - name: Import a role
      ansible.builtin.import_role:
        name: cloud_cpe_cyberark.ccp.retrieve_from_cyberark

 # - name: include cis role
 #   ansible.builtin.include_role: 
 #     name: linux_info
