---
- name: Find instance group for one inventory group
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:

  tasks:
    - name: Import varaible
      ansible.builtin.include_role: 
        name: verify_team_role
        