---
- name: Find instance group for one inventory group
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:

  tasks:
    - name: Get Hosts' information
      uri:
        url: https://192.168.122.10/api/v2/job_templates/?organization=1
        method: GET
        return_content: true
        user: "admin"
        password: "redhat"
        validate_certs: false
        force_basic_auth: true
        status_code: [ 200, 201 ]
      register: result

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Set template ID list
      ansible.builtin.set_fact:
        job_template_ids: "{{ job_template_ids|deafult([]) + [{'id': item.id, 'name': item.name}] }}"
        #job_template_ids: "{{ result['json']['results'] | map(attribute='id') | list }}"
      loop: "{{ result['json']['results'] }}"

    - name: Show job template ID list
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ job_template_ids }}"
      #loop: "{{ result['json']['results'] | map(attribute='id') }}"
      #loop: "{{ result['json']['results'] | map(attribute='name', attribute='id') }}"
      #loop: "{{ result['json']['results'] | selectattr('organization','equalto','1') }}"
