---
- name: Find instance group for one inventory group
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:

  tasks:
    - name: Import varaible
      ansible.builtin.include_vars: 
        file: expected_team_role.yaml

    - name: Get Hosts' information
      uri:
        url: https://192.168.122.10/api/v2/job_templates/?organization=1
        method: GET
        return_content: true
        user: "admin"
        password: "redhat"
        validate_certs: false
        force_basic_auth: true
        status_code: [ 200, 201 ]
      register: result

    #- name: Show output
    #  ansible.builtin.debug:
    #    msg: "{{ result }}"

    - name: Set template ID list
      ansible.builtin.set_fact:
        job_template_ids: "{{ job_template_ids|default([]) + [{'id': item.id, 'name': item.name}] }}"
      loop: "{{ result['json']['results'] }}"

    - name: Show job template ID list
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ job_template_ids }}"
      #loop: "{{ result['json']['results'] | map(attribute='id') }}"
      #loop: "{{ result['json']['results'] | map(attribute='name', attribute='id') }}"
      #loop: "{{ result['json']['results'] | selectattr('organization','equalto','1') }}"

    - name: Get Teams' information
      uri:
        url: https://192.168.122.10/api/v2/teams/?organization=1
        method: GET
        return_content: true
        user: "admin"
        password: "redhat"
        validate_certs: false
        force_basic_auth: true
        status_code: [ 200, 201 ]
      register: result

    - name: Show output
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Set template ID list
      ansible.builtin.set_fact:
        team_ids: "{{ team_ids|default([]) + [{'id': item.id, 'name': item.name}] }}"
      loop: "{{ result['json']['results'] }}"

    - name: Show job template ID list
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ team_ids }}"

    - name: Show job template ID list
      ansible.builtin.include_tasks:
        file: generate_team_roles_data.yaml
      loop: "{{ team_ids }}"
      loop_control:
        loop_var: team

    - name: Show expected_team_role
      ansible.builtin.debug:
        var: expected_team_role