---

- name: Set tempalte list
  ansible.builtin.set_fact:
    configured_template_list: "{{ team_roles | selectattr('name', 'equalto', team_role.name) | selectattr('resource_type', 'equalto', team_role.resource_type) | selectattr('perm', 'equalto', team_role.perm) | map(attribute='resource_name')}}"

- name: Extract {{ team_role.resource_type }} list with {{ team_role.perm }} for {{ team_role.name }}
  ansible.builtin.debug:
    msg: "{{ configured_template_list }}"

- name: Extract full job template list
  ansible.builtin.set_fact:
    job_template_name: "{{ job_template_ids | map(attribute='name') }}"

- name: Extract full job template list
  ansible.builtin.debug:
    msg: "{{ job_template_name }}" 

- name: The job template not in conf list
  ansible.builtin.debug:
    msg: "{{ job_template_name | difference(configured_template_list) }}"
