---
- name: Find instance group for one inventory group
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:

  tasks:
    - name: Get Hosts' information
      uri:
        url: https://192.168.122.10/api/v2/job_templates/
        method: GET
        return_content: true
        user: "admin"
        password: "redhat"
        validate_certs: false
        force_basic_auth: true
        status_code: [ 200, 201 ]
      register: result

    - name: Show
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ result['json']['results'] | selectattr('organization', 'equalto', 1) | map(attribute='name') | flatten | map(attribute='id') | flatten}}"
