- name: Collect config file
  block:
    - name: 'Run the command - {{ cmd }}'
      ansible.builtin.shell: |
        {{ cmd }}
      register: cmd_result
      failed_when:
        - "'find' not in cmd"
        - cmd_result.rc != 0

    - name: Save the command output to the file
      ansible.builtin.copy:
        content: "{{ cmd_result.stdout }}"
        dest: "{{ subdir }}/{{ timestamp }}/command-outputs/{{ cmd | replace(' ', '') | replace('/', '_') }}"
        #dest: "{{ subdir }}/{{ timestamp }}/command-outputs/{{ cmd | replace(' ', '') | replace('/', '_') | replace('*', '_') }}"
      delegate_to: "{{ store_server }}"

  rescue:
    - name: Fail to collect the output of the command - {{ cmd }} 
      ansible.builtin.debug:
        msg: "Fail to collect the output of the command - {{ cmd }}"


