---

- name: Update conf file list
  block:
    - name: "Search file - authorized_keys"
      ansible.builtin.command: find / -type f -name 'authorized_keys'
      register: authorized_keys_files
      changed_when: false
      failed_when: false

    - name: Update the conf file list
      ansible.builtin.set_fact:
        updated_files: "{{ updated_files | default(files) + [ item ] }}"
      when: item is regex("\.ssh/authorized_keys")
      loop: "{{ authorized_keys_files.stdout_lines }}"


- name: Set variables timestamp & subdir
  ansible.builtin.set_fact:
    timestamp: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour|string }}-{{ ansible_date_time.minute|string }}-{{ ansible_date_time.second|string }}"
    subdir: "/tmp/{{ inventory_hostname }}"

- name: Create directory to save collections
  ansible.builtin.shell: |
    mkdir -p "{{ subdir }}/{{ timestamp }}/files"
    mkdir -p "{{ subdir }}/{{ timestamp }}/command-outputs"
  delegate_to: "{{ store_server }}"
