---
- name: Get Hosts' information
  uri:
    url: https://192.168.122.10/api/v2/users/{{ user.id }}/organizations/
    method: GET
    return_content: true
    user: "admin"
    password: "redhat"
    validate_certs: false
    force_basic_auth: true
    status_code: [ 200, 201 ]
  register: result

- name: Show user team info
  ansible.builtin.debug:
    msg: "{{ result.results }}"
    
- name: Set template ID list
  ansible.builtin.set_fact:
    user_list: "{{ user_list|default([]) + [{'id': item.id, 'name': item.username, }] }}"
  loop: "{{ result['json']['results'] }}"
  loop_control:
    label: '{{item.name}}'