---
- name: Get user information
  uri:
    url: https://192.168.122.10/api/v2/users/
    method: GET
    return_content: true
    user: "admin"
    password: "redhat"
    validate_certs: false
    force_basic_auth: true
    status_code: [ 200, 201 ]
  register: result

- name: Set template ID list
  ansible.builtin.set_fact:
    user_list: "{{ user_list|default([]) + [{'id': item.id, 'name': item.username, }] }}"
  loop: "{{ result['json']['results'] }}"
  loop_control:
    label: '{{item.username}}'

- name: Select user based on organization
  ansible.builtin.include_tasks:
    file: 00-01-user-org-info.yaml
  loop: "{{ user_list }}"
  loop_control:
    loop_var: user

- name: Get the team list for each user
  ansible.builtin.include_tasks:
    file: 00-02-user-teamList.yaml
  loop: "{{ user_list_orig }}"
  loop_control:
    loop_var: user

- name: Set  team_user_list
  ansible.builtin.set_fact:
    team_user_list: "{{team_user_list|default([]) + [{'team': team, 'user': user_team|selectattr('team', 'equalto', team)|map(attribute='user')|list }]}}"
  loop: "{{ user_team | map(attribute='team') | list | unique }}"
  loop_control:
    loop_var: team

- name: Show team_user_list
  ansible.builtin.debug:
    msg: "{{ team_user_list }} - {{ expected_team_member }}"


- name: Get the team list for each user
  ansible.builtin.include_tasks: test.yaml
  loop: "{{ expected_team_member | map(attribute='team') | list | unique }}"
  loop_control:
    loop_var: team

#- name: Get the team list for each user
#  ansible.builtin.include_tasks:
#    file: 00-03-restructure-team-user.yaml
#  loop: "{{ expected_team_member | map(attribute='team') | list | unique }}"
#  loop_control:
#    loop_var: team

    