---
- name: Get job_template info based on organization
  uri:
    url: https://{{aap_host}}/api/v2/job_templates/?organization={{org_id}}
    method: GET
    return_content: true
    user: "admin"
    password: "redhat"
    validate_certs: false
    force_basic_auth: true
    status_code: [ 200, 201 ]
  register: result

- name: Set template ID & Name list
  ansible.builtin.set_fact:
    job_template_ids: "{{ job_template_ids|default([]) + [{'id': item.id, 'name': item.name}] }}"
  loop: "{{ result['json']['results'] }}"
  loop_control:
    label: '{{item.name}}'

- name: Show job template ID and Name
  ansible.builtin.debug: var=job_template_ids
