---
- name: Get Teams' information
  uri:
    url: https://192.168.122.10/api/v2/teams/?organization=1
    method: GET
    return_content: true
    user: "admin"
    password: "redhat"
    validate_certs: false
    force_basic_auth: true
    status_code: [ 200, 201 ]
  register: result

- name: Set Team ID list    
  ansible.builtin.set_fact:
    team_ids: "{{ team_ids|default([]) + [{'id': item.id, 'name': item.name}] }}"
  loop: "{{ result['json']['results'] }}"
  loop_control:
    label: '{{item.name}}'
