---
- name: Get Teams' roles information
  uri:
    url: https://192.168.122.10/api/v2/teams/{{ team.id }}/roles/
    method: GET
    return_content: true
    user: "admin"
    password: "redhat"
    validate_certs: false
    force_basic_auth: true
    status_code: [ 200, 201 ]
  register: result

- name: Set Teams' roles list
  ansible.builtin.set_fact:
    team_roles: "{{ team_roles|default([]) + [{'name': team.name, 'perm': item.name, 'resource_name': item.summary_fields.resource_name, 'resource_type': item.summary_fields.resource_type}] }}"
  loop: "{{ result['json']['results'] }}"
  loop_control:
    label: '{{ item.summary_fields.resource_name }} : {{item.name}}'

- name: The Team RBAC
  ansible.builtin.debug:
    var: team_roles