---

- name: Extract full template list
  ansible.builtin.set_fact:
    configured_user_list: "{{ team_user_list | selectattr('team', 'equalto', team) | map(attribute='user') | unique }}"
    exptected_user_list: "{{ expected_team_member | selectattr('team', 'equalto', team) | map(attribute='user') | unique }}"

- ansible.builtin.debug: var=configured_user_list

- ansible.builtin.debug: var=exptected_user_list

- name: Missing user 
  block:
    - name: Debug
      ansible.builtin.set_fact:
        missing_user: "{{ exptected_user_list | difference(configured_user_list) }}"

    - ansible.builtin.debug: var=missing_user

    - name: Ensure all job templates configured for
      ansible.builtin.fail:
        msg: "{{ missing_user }}"
      when: missing_user | length > 0
  rescue:
    - name: Find the missing job template
      ansible.builtin.set_fact:
        err_list: "{{ err_list|default([]) + [ 'Missing user (' + item + ')' + ' for team (' + team + ')' from AAP Configuration ] }}"
      loop: "{{ missing_user }}"

    - name: The job template not in conf list
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ err_list }}"