---
- name: Ensure job templated configured
  ansible.builtin.include_tasks:
    file: 09-01-ensure-team-user.yaml
  loop: "{{ expected_team_member | map(attribute='team') | list | unique }}"
  loop_control:
    loop_var: team