---
- name: Collect job tempalte information
  ansible.builtin.include_tasks:
    file: 01-collect-job-templates-info.yaml

- name: Collect workflow job tempalte information
  ansible.builtin.include_tasks:
    file: 02-collect-workflow-template-info.yaml

- name: Collect team information
  ansible.builtin.include_tasks:
    file: 03-collect-teams-information.yaml

- name: Collect team RBAC information
  ansible.builtin.include_tasks:
    file: 04-collect-team-RBAC-information.yaml

- name: Ensure all teams configred
  ansible.builtin.include_tasks:
    file: 05-ensure-team-no-missing.yaml

- name: Ensure team RBAC job template configured
  ansible.builtin.include_tasks:
    file: 06-ensure-job-templates.yaml

#- name: Ensure team RBAC workflow template configured
#  ansible.builtin.include_tasks:
#    file: 07-ensure-workflow-templates.yaml