---
#- name: Initialization
#  ansible.builtin.include_tasks:
#    file: 00-pre-work.yaml

#- name: Debug
#  ansible.builtin.debug:
#    var: expected_team_role

- name: Collect job tempalte information
  ansible.builtin.include_tasks:
    file: 01-collect-job-templates-info.yaml

- name: Collect workflow job tempalte information
  ansible.builtin.include_tasks:
    file: 02-collect-workflow-template-info.yaml

- name: Collect team information
  ansible.builtin.include_tasks:
    file: 03-collect-teams-information.yaml

- name: Collect team RBAC information
  ansible.builtin.include_tasks:
    file: 04-collect-team-RBAC-information.yaml

- name: Collect team RBAC information
  ansible.builtin.include_tasks:
    file: 05-ensure-team-no-missing.yaml