---
- name: Collect job tempalte information
  ansible.builtin.include_tasks:
    file: 01-collect-job-templates-info.yaml

- name: Collect workflow job tempalte information
  ansible.builtin.include_tasks:
    file: 02-collect-workflow-template-info.yaml

- name: Collect team information
  ansible.builtin.include_tasks:
    file: 03-collect-teams-information.yaml

- name: Collect team RBAC information
  ansible.builtin.include_tasks:
    file: 04-collect-team-RBAC-information.yaml

- name: Collect user team information
  ansible.builtin.include_tasks:
    file: 05-collect-team-user-info.yaml

- name: Ensure all teams configred
  ansible.builtin.include_tasks:
    file: 06-ensure-team-no-missing.yaml

- name: Collect user team information
  ansible.builtin.include_tasks:
    file: 09-ensure-team-user.yaml

- name: The job template not in conf list
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ err_list }}"
  when: err_list | length > 0