---
- name: Collect job tempalte information
  ansible.builtin.include_tasks:
    file: 01-collect-job-templates-info.yaml
    
- name: Collect team information
  ansible.builtin.include_tasks:
    file: 03-collect-teams-information.yaml

- name: Collect user team information
  ansible.builtin.include_tasks:
    file: 08-collect-team-user-info.yaml

- name: Collect user team information
  ansible.builtin.include_tasks:
    file: 09-ensure-team-user.yaml